baseURL = 'https://ana.help'
languageCode = 'en-us'
title = 'Ana Meisel'
theme = 'hugo-PaperMod'
description = '㋡'

[social]
twitter = "anmeisel"
# facebook_admin = "123456789"  # optional for Facebook insights

[markup.goldmark.renderer]
unsafe = true

[author]
name = "Ana Meisel"
email = "hi@ana.help"
