baseURL = 'https://ana.help'
languageCode = 'en-us'
title = 'Ana Meisel'
theme = 'hugo-PaperMod'
description = '㋡'

[markup.goldmark.renderer]
unsafe = true

[author]
name = "Ana Meisel"
email = "hi@ana.help"
